#author: Łukasz Komosa
title: Łukasz Komosa
email: lukasz.komosa@komluk.com
description: Software Developer at FinAi
url: "https://komluk.github.io"

# Social Profiles
github_username: komluk
facebook_username: komluk91
linkedin_username: komluk

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate