title: Łukasz Komosa
email: lukasz.komosa@komluk.com
description: A Blog Theme by komluk
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://komluk.github.io"

# Social Profiles
github_username: komluk
facebook_username: 'komluk91'

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate